apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*
        Refresh_Interval 5

    [FILTER]
        Name         kubernetes
        Match        kube.*
        Kube_URL     https://kubernetes.default.svc:443
        Merge_Log    On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name        es
        Match       *
        Host        116.103.226.146
        Port        9200
        HTTP_User   elastic
        HTTP_Passwd iRsUoyhqW-CyyGdwk6V_
        Index       baohb_0983155487
        Logstash_Format On
        Logstash_Prefix app-logs
        Retry_Limit False
        tls         On
        tls.verify  Off
        Replace_Dots On
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On