apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}
