- name: Create docker network
  docker_network:
    name: "{{ docker_network_name }}"  

- name: Deploy MongoDB container
  docker_container:
    name: mongo_db
    image: mongo:5.0
    restart_policy: unless-stopped
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - name: "{{ db_network_api_db }}"