apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-main-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  
  hostPath:
    path: /mnt/data/prometheus-main  
  volumeMode: Filesystem