apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-servicemonitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: web
  namespaceSelector:
    matchNames:
      - default 
  endpoints:
    - port: web
      interval: 30s
      path: /metrics
