appName: web

namespace: web

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  repository: helloitsurdvq/web
  tag: latest

service:
  nodePort: 30080
