project: default
source:
 repoURL: 'https://github.com/helloitsurdvq/VDT2024-api'
 path: charts
 targetRevision: HEAD
 helm:
   valueFiles:
     - values.yaml
destination:
 server: 'https://kubernetes.default.svc'
 namespace: api
syncPolicy:
 syncOptions:
   - CreateNamespace=true