name: Unit Test Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

# env:
#   API_DIR: ./app/api

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd app/api
          npm install

      - name: Run unit tests
        env:
          MONGO_URL: mongodb://localhost:27017/testdb
        run: |
          cd app/api
          npx mocha test/trainee.js
